### PR TITLE
Fix `FilesAndFolders` in `Glob`

### PR DESCRIPTION
**Pull request by miniBill**

### CODE REVIEW

**Comment by dillonkearns** [comment]
I just caught this as well! I think I beat you to the fix on master:

https://github.com/dillonkearns/elm-pages/blob/e0c363a4c3ba461a04ce87ee7303b642b4265885/src/BackendTask/Glob.elm#L1046-L1065

So I think we can close this one. Thanks for the PR!

**Comment by miniBill** [comment]
With some more testing I actually think neither my version nor yours are correct? If I try to run it and target a socket file it just... hangs

**Comment by miniBill** [comment]
[This, by the way, is a failure mode I've observed in the past: if something happens such that Elm doesn't get an answer it expects the whole script just... hangs in there]

**Comment by dillonkearns** [comment]
Yeah, the DX for working on the internal implementations for BackendTask runners is not so great, I am annoyed by it regularly as well. Would be nice to improve the error handling for faster iteration in development on those implementations.

**Comment by miniBill** [comment]
My DX is `yarn add -D ../elm-pages; yarn elm-pages run script/path`

**Comment by dillonkearns** [comment]
Oh yeah, I just work on example scripts in `examples/end-to-end/script/src/` and run `npx elm-pages run script/src/MyExample.elm`. That part works great.

I meant the DX of things hanging instead of just having a clear error message and exiting when something goes wrong in the implementations in `render.js`. That would be nice to improve for iteration in dev.

**Pull request closed without merging**
