### PR TITLE
Fix elm-codegen bindings

### LINKED ISSUE #501: Build failures with 3.0.17
We just tried updating from 3.0.16 to 3.0.17 at work, but started getting a bunch of Elm compiler errors when running `elm-pages build`:

image

Is it possible that the update to `elm-codegen` v5 broke code generation in some cases, or is this likely a symptom of something else? (The error happens both locally and in CI, including after deleting `.elm-pages`, `elm-stuff`  and `node_modules`, so I don't _think_ it's a corrupt build cache or anything like that.)

(And yes, as you might be able to guess from the paths we are indeed using `elm-pages` for our [public web site](https://generative.vision)! Thanks for all your work on it! :pray:)

### PR DESCRIPTION
**Pull request by miniBill**
Fixes #501

### CODE REVIEW

**Comment by miniBill** [comment]
I don't think the failure is caused by my change? :thinking:

**Comment by dillonkearns** [comment]
Yes, that one is flaky I’ll rerun it.

**Comment by miniBill** [comment]
Failed again :(

**Comment by dillonkearns** [comment]
I just rolled out a release with this, but it doesn't look like it's resolved. I'm getting this error when I upgrade the starter repo:

```
You are trying to import a `Pages.ProgramConfig` module:

34| import Pages.ProgramConfig
```

**Comment by dillonkearns** [comment]
I'm not getting the `Interal.ApiRoute` error anymore, though, so maybe that part was fixed?

**Comment by miniBill** [comment]
The `Pages.ProgramConfig` is because `Pages.Internal.Platform.Cli.cliApplication` has a `Pages.ProgramConfig.ProgramConfig` in its signature, so when generating the binding `elm-codegen` correctly infers the type of the argument to be `Pages.ProgramConfig.ProgramConfig` and then when generating `Main.elm` it incorrectly imports it. I think the simplest solution is to introduce a local alias.

**Comment by miniBill** [comment]
The `Pages.ProgramConfig` import is fixed in https://github.com/dillonkearns/elm-pages/pull/503

**Pull request merged**
