### PR TITLE
Try prerender-trigger event only after body has been updated to make sure Elm has rendered.

### LINKED ISSUE #40: HTML from build sometimes doesn't include content
Hey 👋 Thanks for this great project!

I noticed that sometimes when I make a build, the resulting static HTML says `Missing content` (ie. the content isn't there). Also, sometimes the static–html content is wrong, instead of missing. For example, sometimes I'm getting content for the index page instead of the blog article.

It appears to happen randomly, also tested it with removing the `.cache` directory.

### PR DESCRIPTION
**Pull request by dillonkearns**
Fixes #40.

### CODE REVIEW

**Comment by icidasset** [comment]
Hey 👋  I wanted to test this, but I'm getting the following error. Probably not because of this PR though?

```
emittingTypeError: Cannot read property 'forEach' of undefined
    at /Users/icidasset/Work/fission-landing-prototype/node_modules/elm-pages/generator/src/add-files-plugin.js:57:28
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/icidasset/Work/fission-landing-prototype/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/icidasset/Work/fission-landing-prototype/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/icidasset/Work/fission-landing-prototype/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/Users/icidasset/Work/fission-landing-prototype/node_modules/webpack/lib/Compiler.js:278:9)
    at /Users/icidasset/Work/fission-landing-prototype/node_modules/webpack/lib/Compiler.js:681:15
    at eval (eval at create (/Users/icidasset/Work/fission-landing-prototype/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 ERROR  Command failed with exit code 1.
```

**Comment by dillonkearns** [comment]
Hmm, maybe try this? `npm install --save dillonkearns/elm-pages#prerender-trigger-after-view-function`

I'm not so familiar with that syntax, could be a yarn vs npm issue?

**Comment by dillonkearns** [comment]
Closing in favor of #62.

**Comment by icidasset** [comment]
@dillonkearns Um, so sorry, but, my PR was actually set to merge into this PR. So you should merge this one into master. No changes are in master now 👀

**Comment by dillonkearns** [comment]
Whoops, I just saw that

**Comment by dillonkearns** [comment]
Released as NPM package version 1.2.4 👍

**Pull request merged**
