### PR TITLE
Handle the base in the `Path` module

### LINKED ISSUE #217: `elm-pages build --base sub` does not render correctly
The dev server strips the base properly. But when I try to build, the index is rendered into a subfolder and contains a rendered error message about it being an invalid route. See this [test HTML output for an index file](https://github.com/dillonkearns/elm-pages/pull/237/files#diff-a07fa31cd40645630c26c5ab3a1acc95711cb0b608a4d91c6a75ec5689cd8634R28) for an example.

# Reproduction
1. Check out https://github.com/Y0hy0h/unnecessarily-bad-design/tree/e93e004dcd3cfdc81cf67a1eb23c01d1a095ea38. (I currently don't have a simpler elm-pages repo. The `./examples` don't build for me.)
2. `npm install`
3. `npm build -- --base sub`
4. Look into `./dist`. There is a `./dist/sub/index.html` that says "Page Not Found".

### PR DESCRIPTION
**Pull request by Y0hy0h**
This fixes #217.

I was playing around with the code to see if I could fix that issue. The solution I ended up with is actually close to what Dillon and I discussed on slack regarding how the base is handled.

With this PR that the `Path.elm` is generated to allow inlining the `baseUrl` at compile-time and make `Path.toAbsolute` (which prepends the `baseUrl`) synchronous. I left the `baseUrl` in `Route.elm`, because of the `Route.urlToRoute` function that uses it.

This change cleared up my mental model of how to use paths: Just store everything as a `Path` (via e.g. `Path.fromString` or `Route.toPath`) and when I need to have the URL as a `String` to paste into e.g. a `src` attribute, I call `Path.toString` on it. Therefore `Path`s can be anything that is located on my site.

I've marked this as a draft, because I'm not sure if this solution is what you, Dillon, had in mind. Also there are some things left to do, like the `<head>` tags not having the base prepended and the tests have to be updated.

### CODE REVIEW

**Comment by Y0hy0h** [comment]
@dillonkearns If this is the right direction to go into, you can tell. I'll see if I'll find some time to work on this more.

**Comment by dillonkearns** [comment]
@Y0hy0h thinking out loud a bit, some pros and cons are:

Pro
- It's convenient to use a generated Path module
- It does the right thing if you try to build up a Path (doesn't point you to a URL without a base)

Cons
- It's a little implicit and may be surprising (maybe users might expect that they need to add the base since it's added implicitly?)
- The docs would live locally, not on the package site
- Published code can't depend on the `Path` module

One other possible direction could be to generate something like a `Pages.base : BasePath`. Then getting `Path.toAbsolute` (or `toString`) would require passing in that value. That would sort of have the reverse problem compared to the pros and cons above.

I'm traveling at the moment so I haven't had a chance to think about it much, but that's just a brain dump to get the thoughts flowing a bit. Any thoughts on all that?

**Comment by Y0hy0h** [comment]
@dillonkearns Thanks for your feedback! Take your time traveling and respond when it's convenient to you! :)

I realize that I mixed up two things in `Path`:
- It takes care of constructing a valid path without the need to worry about slashes, and
- it provides a way to point to a part of your elm-pages site, abstracting away the base so that you can configure the base at build-time.

I agree that it's cleaner to separate the two. Since that slash-handling is quite common and you might want to refer to it from published code, `Path` should probably stay as it currently is.

To solve the second issue, a `Pages.base` and especially something like a `Pages.pathToAbsoluteUrl : Path -> String` would be great! The only use case I can think of where you're concerned about the base is to construct URLs, so that should take care of that.

Since people who want to configure the base will need to use the `--base` flag, we also have a good place to point people to a `Pages.pathToAbsoluteUrl` method. If they haven't used that method before, they might need to migrate some call sites, but it should be a straight-forward migration.

I'll have a go at that approach and open a new PR, so that we're able to compare them more easily.

**Comment by dillonkearns** [comment]
Sounds great, thank you @Y0hy0h!

**Pull request closed without merging**
