### PR TITLE
https support for dev server

### PR DESCRIPTION
**Pull request by sheakelly**
Adding new `--https` argument to dev server command
Using devcert package to manage creation and installation of cert

### CODE REVIEW

**Comment by dillonkearns** [comment]
Hello @sheakelly, thank you for the PR! I'm not too familiar with the workflow of using https for local development. Could you explain how the SSL cert can be passed in? Or is it not passed in at all with this?

I notice that some tools, like `elm-live` for example, have command line options like this:

```shell
elm-live --help
    -S, --ssl [ssl]                  Start an https server instead of http. (default: false)
    -c, --ssl-cert [cert]            Pass in a relative path to your own ssl cert. (default: false)
    -k, --ssl-key [key]              Pass in a relative path to your own ssl key. (default: false)

...
```

But I don't think this PR has a way to pass in an SSL cert or key. Is that a separate feature to be able to use a specific cert, and the way it's setup here just allows you to use https on localhost but without specifying a specific SSL cert?

If that's the case, it would be helpful to get a better sense of how to test it. Do I just start a dev server with this branch and expect to see it working with https, or are there any other steps or things to test?

Thank you!

**Comment by sheakelly** [comment]
Hi @dillonkearns. My implementation was inspired by the gatsby cli. It uses the devcert package to automatically generate a cert that the package stores in the appropriate key store (after the the user is prompted to enter a password). I have not needed to use an existing cert and/or key file before so I am not really sure the use case there.

To test it I just ran `elm-pages dev --https` on the docs site. The server should start as normal with a 'https' url 
```
> elm-pages dev --https

Ran elm make ./.elm-pages/TemplateModulesBeta.elm in 438ms
Ran elm make .elm-pages/TemplateModulesBeta.elm in 441ms
elm-pages dev server running at <https://localhost:1234>
```

image

**Comment by dillonkearns** [comment]
Excellent, thanks for all that background @sheakelly! That sounds great. I tried it out locally and it was working nicely.

The one thing I notice is that http://localhost:1234 does not redirect. That could be nice to automatically handle http:// and redirect to https, do you know if that's possible?

**Comment by sheakelly** [comment]
Hi @dillonkearns. It is technically possible to automatically handle the redirect from http -> https. Looks like it would involve setting up a reverse proxy in node. 

There are a few way of doing it but they all seem fairly complicated. e.g. expressjs can do this https://docs.divio.com/en/latest/how-to/node-express-force-https/ or another node package e.g. https://github.com/vinsonchuong/httpx-server

Another option could be to use a different port for https and http. I think that chrome remembers the protocol based on the host not including the port so that does not really help with the original problem.

**Comment by dillonkearns** [comment]
Got it, thanks so much for researching that @sheakelly 🙏 

Given that it's fairly complex, I think it's reasonable to start without the redirects as this provides a useful feature on its own without the redirects. We could always revisit that in the future if it seems important.

Thanks so much for this PR, I really appreciate your thoughtful work on this!

**Comment by dillonkearns** [comment]
I need to work on a few parts of the API to avoid making breaking changes when I touch the internals. So once I figure something out for that, then I'll do a release that will include this new feature. I created a placeholder for that issue just to track the progress in case you'd like to subscribe to that thread: https://github.com/dillonkearns/elm-pages/issues/256.

Thank you!

**Pull request merged**
