### PR TITLE
Provide image dimensions

### LINKED ISSUE #104: Access to image dimensions
Similar to #36, it would be useful to have access to the actual image dimensions.

My use case is that I would like to set the `width` and `height` HTML attributes on the ``, to prevent the layout from popping after the image has been loaded. By setting the intrinsic dimensions, the browser is able to reserve the appropriate amount of space even before the image resource is loaded.

I imagine it could look something like `ImagePath.width Pages.images.funnyGif`. That means elm-pages would statically store the dimensions of all images in `Pages` from where I could simply access it.

### PR DESCRIPTION
**Pull request by Y0hy0h**
Closes #104.

Adds a function that exposes the intrinsic dimension in pixels for internal `ImagePath`s.

Note that currently images are not tested with the `Pages.elm` snapshot test. This is because there is no `images` folder in the root and thus no images are included there. I have tested it locally with one image, though.

## Demonstration
1. Clone the [elm-pages-starter repo](https://github.com/dillonkearns/elm-pages-starter).
2. In `src/Page/Article.elm` at the bottom replace the definition of `articleImageView` with
    ```
    articleImageView : ImagePath Pages.PathKey -> Element msg
    articleImageView articleImage =
        Element.column []
            [ Element.image
                [ Element.width Element.fill ]
                { src = ImagePath.toString articleImage
                , description = "Article cover photo"
                }
            , Element.text
                (ImagePath.dimensions articleImage |> Maybe.map (\dims -> String.fromInt dims.width ++ " by " ++ String.fromInt dims.height) |> Maybe.withDefault "none")
            ]
    ```
3. Run `npm run start`.
4. Open http://localhost:3000/blog/hello.

### CODE REVIEW

**Comment by dillonkearns** [comment]
Thank you so much @Y0hy0h! It looks like it's working perfectly, great work!

I was able to add a call to `process.chdir(__dirname)` to get it to generate the snapshot and actually run sharp with your changes. Pretty nice to get that added confidence with a tricky thing like that.

https://github.com/dillonkearns/elm-pages/blob/007c9c823f2ec1e7ef65c4b646b3ebb8030c5cb5/tests/__snapshots__/generated-files.test.js.snap#L77-L86

Looking forward to seeing what people do with this new functionality! Thanks again!

**Comment by Y0hy0h** [comment]
I'm gonna add `code` to my contributions. (The [all-contributors notes](https://allcontributors.org/docs/en/repository-maintainers) tell me to. 😜)

@all-contributors add @Y0hy0h for code

**Comment by Y0hy0h** [comment]
Sorry bot, I didn't think you'd insist on good manners...

@all-contributors please add @Y0hy0h for code

**Comment by dillonkearns** [comment]
Thanks for catching that @Y0hy0h! I merged in the all-contributors PR 👍

**Pull request merged**
