### PR TITLE
Move subheadings in docs pages to inline "On This Page" widget.

### PR DESCRIPTION
**Pull request by dillonkearns**

### CODE REVIEW

**Comment by dillonkearns** [comment]
Here's a live preview: https://deploy-preview-388--elm-pages.netlify.app/docs/.

**Comment by kyasu1** [comment]
Hi, thank you for the fixes. I think the layout is perfect and looks like the *standard* docs sites ! 

One thing I noticed is that the On This Page menu scrolls out with the content in the mobile size. I think it is better to always be under the top nav menu.

**Comment by dillonkearns** [comment]
Hello @kyasu1, when I view the site on iPhone SE dimensions it doesn't scroll out horizontally but adds a collapsed nav section to the top:

Untitled


I think I'll close this issue for now, but I would welcome a pull request if you think it could be cleaned up in some way. If so, please share a screenshot of a mobile device (like the one I did above in a Chrome-based browser) that shows the horizontal scroll for my reference. Thank you again for all the feedback!

**Comment by kyasu1** [comment]
Ah, I thought it would be better to fix the `On this page` menu on scrolling as implemented for [vercel's doc site](https://vercel.com/docs/frameworks). But this clutter on small screens, and it is a matter of taste and page design. I think the current one is fine as it is. Thank you for the updates!

**Pull request closed without merging**
